#!/usr/bin/env bash
## Run ncmpcpp with alternate config

# i3 directory
DIR="$HOME/.config"

CONFIG="$DIR/kitty/kitty.conf"

kitty --class 'Music,Music' --config-file "$CONFIG" \
	  --start-as=normal --keep-focus --detach \
      --window-size=105x22 \
      --command='~/.config/.ncmpcpp/scripts/ncmpcpp-art'
