#!/usr/bin/env bash

DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/screenshot.rasi"
SHOT="$DIR/scripts/i3_screenshot"

prompt='Screenshot'
mesg="Directory :: $(xdg-user-dir Pictures)/Screenshots"
layout="$(grep 'USE_ICON' "$RASI" | cut -d'=' -f2)"

if [[ "$layout" == 'NO' ]]; then
  option_1="Capture Desktop"
  option_2="Capture Area"
  option_3="Capture Window"
  option_4="Capture in 5s"
  option_5="Capture in 10s"
else
  option_1="  Capture Desktop"
  option_2="  Capture Area"
  option_3="  Capture Window"
  option_4="  Capture in 5s"
  option_5="  Capture in 10s"
fi

chosen="$(
  printf '%s\n%s\n%s\n%s\n%s\n' "$option_1" "$option_2" "$option_3" "$option_4" "$option_5" |
    rofi -dmenu -p "$prompt" -mesg "$mesg" -markup-rows -format i -theme "$RASI"
)"

case "$chosen" in
  0) "$SHOT" --now ;;
  1) "$SHOT" --area ;;
  2) "$SHOT" --win ;;
  3) "$SHOT" --in5 ;;
  4) "$SHOT" --in10 ;;
esac
