Net/ThemeName "Adwaita"
Net/IconThemeName "Adwaita"
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 24
Gtk/FontName "Noto Sans 10"
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/EnableAnimations 1
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
